backend:
  name: github
  repo: capelito-tv-show/suganote

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog/{{field.slug}}
    file: index.md
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - {label: Slug", name: "slug", widget: "string"}
      - { name: thumnail, label: thumnail, widget: image}
      - { name: body, label: Body, widget: markdown }