backend:
  name: github
  repo: capelito-tv-show/suganote

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    slug: "{{fields.slug}}"
    file: "content/blog/{{fields.path}}.md"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - {label: "Slug", name: "slug", widget: "string"}
      - { name: description, label: Description }
      - { name: thumnail, label: thumnail, widget: image}
      - { name: body, label: Body, widget: markdown }